[application]
name = "realec-web"
out_dir = "docs"
asset_dir = "public"
[web.app]

# HTML title tag content
title = "e-c-web"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
